name: HEXO DEPLOY
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-15

    steps:
    - name: Checkout              
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Setup Node        
      uses: actions/setup-node@v1
      with:
        node-version: "23.3.0"

    - name: Config Key
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.BLOG }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa_blog
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa_blog
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "wdhuang927@gmail.com"
        git config --global user.name "WhaleGe"

    - name: NPM install       
      run: |
        npm install hexo-cli -g
        npm install

    - name: Hexo Deploy           
      run: |
        hexo clean
        hexo g
        hexo d
